### PR TITLE
feat: implemented mn fv tables in step 2 & 3

### PR DESCRIPTION
**Pull request by DanielLyleWilliamWarren**
- Updated table in step 2 & 3 based on conversation with AB this am. 
- Prevent Errors when data returned from API is NULL. (To test: use review intervention ID 6)

To Test:

1. Inspect > Application > Clear site data 
2. Select intervention: id 5
3. View steps 1 > 2 > 3 ('Other Mn in Premix' table should be empty).
4. Return to step 1 > Add Mn to Premix > View step 2 > view step 3 (Mn should be visible in 'Other Mn in Premix' table)

image

### CODE REVIEW

**Review by Fuhji — CHANGES_REQUESTED** [review]
I'm getting an error when navigating from baseline --> confirm and continue:

image

pointing to `this.createAvNutrientLevelTable(rawData);` as the source

https://github.com/micronutrientsupport/micronutrient-support-tool/pull/1057/files#diff-7464d244e5ddc98860b50e99ca6bbc2a9113807008231e9b7df9fbddda56237cR69

I noticed because the sidebar doesnt move from 1. to 2. but the page content does, so that got me looking closer. 2. to 3. does work though.

This error shows when the user has *not* selected 'Add Micronutrient' in baseline, so its not handling the page change when cant find `cachedMnInPremix` from local cache. Adding a mn does prevent the console error but doesnt fix the sidebar stage jump from 1 to 3.

**Comment by jlczapski** [comment]
image

Getting loading issues when testing the deployed URL, infinite skeleton content loading?

**Comment by Fuhji** [comment]
@DanielLyleWilliamWarren  I'm still seeing the same console error as before?

```
main.aa9de3152b3635e6.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'forEach')
TypeError: Cannot read properties of null (reading 'forEach')
    at M.createAvNutrientLevelTable (main.aa9de3152b3635e6.js:1:193090)
```

**Comment by jlczapski** [comment]
> @DanielLyleWilliamWarren I'm still seeing the same console error as before?
> 
> ```
> main.aa9de3152b3635e6.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'forEach')
> TypeError: Cannot read properties of null (reading 'forEach')
>     at M.createAvNutrientLevelTable (main.aa9de3152b3635e6.js:1:193090)
> ```

image

This error for me too

**Comment by Fuhji** [comment]
https://preview1057--micronutrientsupport-tool.netlify.app/quick-maps/food-systems/cost-effectiveness/intervention-baseline?country-id=ETH&mnd-id=Ca&measure=food%20systems&age-gender-group-id=WRA&intIds=%5B5%5D

cleared site data ✅ 
using ID5 for intervention ✅ 

The only intervention page that works for me is stages 2 and 3. stages 1, 4 and 5 now stuck on skeleton loading

**Comment by DanielLyleWilliamWarren** [comment]
> https://preview1057--micronutrientsupport-tool.netlify.app/quick-maps/food-systems/cost-effectiveness/intervention-baseline?country-id=ETH&mnd-id=Ca&measure=food%20systems&age-gender-group-id=WRA&intIds=%5B5%5D
> 
> cleared site data ✅ using ID5 for intervention ✅
> 
> The only intervention page that works for me is stages 2 and 3. stages 1, 4 and 5 now stuck on skeleton loading

Think this is being caused by API failure? (Getting 500s). Exact same behavior and errors on develop deployment: https://develop--micronutrientsupport-tool.netlify.app/quick-maps/food-systems/cost-effectiveness/intervention-baseline?country-id=ETH&mnd-id=Ca&measure=food%20systems&age-gender-group-id=WRA&intIds=%5B5%5D .

**Comment by Fuhji** [comment]
@DanielLyleWilliamWarren when adding Other mn to premix in Stage 1 it then loads in the following views. However, when editing the values in standard/target nutrient level or optional user aveager, then clicking 'confirm and continue, this value does not persist through to steps 2 or 3?

Given that the sectionis Baseline Assumptions, should there be any edits available? There are no POST/PATCH requests being sent when moving from page 1 to 2?

**Comment by DanielLyleWilliamWarren** [comment]
Closing as MR is trying to do too man things and causing issues.

**Pull request closed without merging**
