### PR TITLE
Dw compound selection persist

### PR DESCRIPTION
**Pull request by DanielLyleWilliamWarren**
- Stores selected mn compounds for each intervention in local storage. 

To Test: 
- Variables: Malawi & Calcium
- Load 2 interventions (ID 4 & 5)
- Select as many Mn as you like in stage 1
- Select compound for each mn
- Move between stages 1-3
- Repeat for other intervention
- Review initial intervention and make sure selected micronutrients and compounds are selected

### CODE REVIEW

**Comment by Fuhji** [comment]
adding a new Mn the drop down text is blank

image

is this because there are then sub-choices to be made e.g. Zinc > then pick Zinc Oxide or Sulphate?

If yes, could your use groups with `mat-select` e.g. 

at this page 

image
 
use

image

**Comment by bgsandan** [comment]
Yes, I believe so, though a default/placeholder to indicate the need to select may provide better UX?

--

Responded before update - that could work...
________________________________

**Comment by DanielLyleWilliamWarren** [comment]
> adding a new Mn the drop down text is blank
> 
> image
> 
> is this because there are then sub-choices to be made e.g. Zinc > then pick Zinc Oxide or Sulphate?
> 
> If yes, could your use groups with `mat-select` e.g.
> 
> at this page
> 
> image
> 
> use
> 
> image

Yes that is how it should function, some placeholder text is needed 'Please select compound'

**Review by Fuhji — CHANGES_REQUESTED** [review]
LGTM

suggest adding placeholder text to select compound as minimal UX to clarify next step

**Comment by Fuhji** [comment]
Question: should you be able to add multiple compounds e.g. Iron ferruous fumarate AND electrolytic iron? Having one iron compound stops you adding any other iron compounds @bgsandan 

Dont think this Q should stop this being merged as the PR has been resolved

**Review by Fuhji — APPROVED** [review]

**Comment by DanielLyleWilliamWarren** [comment]
> Question: should you be able to add multiple compounds e.g. Iron ferruous fumarate AND electrolytic iron? Having one iron compound stops you adding any other iron compounds @bgsandan
> 
> Dont think this Q should stop this being merged as the PR has been resolved

It is possible to add the same micronurient twice, so iron could be added 7 times to give the user visibility of all the compounds associated to Fe

**Pull request merged**
