### PR TITLE
139 map tools layout

### LINKED ISSUE #139: Reduce header size of /maps-tool page to increase visibility of tool option cards
Tool options: Quick MAPS, My MAPS etc. are too far down the page and may be missed 'below the fold'.

Also consider updating to allow 4 cards to sit side-by-side as per the Figma prototype

### PR DESCRIPTION
**Pull request by jon571**
closes #139 
- attempt to reduce top areas of pages enough to show at least a taste of the content below
- switch the main scroll from body to html to interact better when dialogs are shown

### CODE REVIEW

**Comment by jon571** [comment]
Hi @Fuhji .
Feel free to say no, no, no this isn't how it is supposed to be done if I've gone against what you originally put in! :-)

**Comment by Fuhji** [comment]
Only comment is the thresholds for responsive causing boxes to now be squashed.

New PR:

image


Original 

image

**Comment by jon571** [comment]
Good spot @Fuhji 
Update pushed.  Better?

**Comment by Fuhji** [comment]
bueno :)

**Pull request merged**
