### PR TITLE
Dw intervention comparison scaffold

### PR DESCRIPTION
**Pull request by DanielLyleWilliamWarren**
Scaffolded comparison intervention area and created card to display comparisons.

### CODE REVIEW

**Comment by Fuhji** [comment]
Clicking through the new pages to test and wondered if it would help identify working vs not working functionality to disable buttons with no responses, or to disable other elements which perhaps half-work? There are lots of new bits of content here that it would help (me at least!) to clarify the scaffolding.

@pautva any other thoughts on how to indicate content is WIP?

**Comment by Fuhji** [comment]
also @DanielLyleWilliamWarren your scaffolding covers #667 #670 i think

**Comment by DanielLyleWilliamWarren** [comment]
> also @DanielLyleWilliamWarren your scaffolding covers #667 #670 i think

I've updated both issues with what has been delivered in the current implementations until we have an API to work with and we can get some CRUD functionality implemented.

**Comment by Fuhji** [comment]
tests failed :( @DanielLyleWilliamWarren

**Comment by Fuhji** [comment]
@DanielLyleWilliamWarren button looks to be disabled but clicking on it still triggers the navigation?
image

**Comment by DanielLyleWilliamWarren** [comment]
@Fuhji my bad, had pushed change yesterday to wrong branch!

**Comment by pautva** [comment]
> 

We could have a WIP sign in the bottom right to indicate which pages are still under development. 
wip

On hover, it could display a more detailed description of what it means.

Cost Effectiveness-wip

When it's ready for review, we could change it:

image

**Review by bgsandan — APPROVED** [review]
Looks good to me

**Pull request merged**
